services:
  nginx:
    image: nginx:1.27.2
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"  # 添加 HTTPS 端口映射
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # 挂载 SSL 文件
      - ./dist:/usr/share/nginx/html:ro  # 前端构建文件
    depends_on:
      - app

  mongodb:
    image: mongo:8.0.3
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: backend.dockerfile
    container_name: nodejs_app
    environment:
      PORT: 3000
      MONGO_URI: mongodb://admin:secret@mongodb:27017
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: